services:
  terraform-init:
    image: hashicorp/terraform:1.5
    working_dir: /terraform
    volumes:
      - ./terraform:/terraform
      - ./credentials:/credentials
    entrypoint: [""]
    command: >
      sh -c "
      terraform init &&
      terraform plan &&
      terraform apply -auto-approve
      "
    restart: on-failure

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      # UTF-8 encoding support
      KAFKA_OPTS: "-Dfile.encoding=UTF-8"
      LANG: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # UTF-8 encoding support
      KAFKA_OPTS: "-Dfile.encoding=UTF-8"
      LANG: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      # UTF-8 encoding support
      JAVA_OPTS: "-Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8"
      LANG: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"
